gems: [jekyll-paginate]
excerpt_separator: ""
highlighter: rouge
markdown: kramdown
url: http://awesomeroots.github.io
title: Awesome Roots
tagline: development team blog
description:
paginate: 5
